databases:
  - name: animalguardian-postgres
    plan: starter

services:
  - type: web
    name: animalguardian-backend
    env: python
    plan: starter
    autoDeploy: true
    rootDir: backend
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: >
      python manage.py migrate --noinput &&
      gunicorn animalguardian.wsgi:application
      --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: DJANGO_SETTINGS_MODULE
        value: animalguardian.settings
      - key: SECRET_KEY
        sync: false
      - key: ALLOWED_HOSTS
        value: animalguardian-backend.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: animalguardian-postgres
          property: connectionString
      - key: REDIS_URL
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: AFRICASTALKING_USERNAME
        sync: false
      - key: AFRICASTALKING_API_KEY
        sync: false
      - key: DEFAULT_FROM_EMAIL
        value: "no-reply@animalguardian.rw"
      - key: WEB_CONCURRENCY
        value: "3"
    disk:
      name: media
      mountPath: /opt/render/project/src/media
      sizeGB: 2

